# Generated by Django 3.2 on 2022-10-27 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RequestForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=250)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=11)),
                ('event_type', models.CharField(max_length=300)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('event_desc', models.TextField()),
                ('entertainer', models.BooleanField(blank=True, null=True)),
                ('food', models.BooleanField(blank=True, null=True)),
                ('member', models.BooleanField(blank=True, null=True)),
            ],
        ),
    ]
