# Generated by Django 3.2 on 2022-10-27 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('roomhire', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='RequestForm',
        ),
    ]
