# Generated by Django 3.2 on 2022-10-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('roomhire', '0002_delete_requestform'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoomHire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=300)),
                ('email_address', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=11)),
                ('date_of_event', models.DateTimeField()),
                ('start_time', models.CharField(max_length=20)),
                ('end_time', models.CharField(max_length=20)),
                ('num_people', models.CharField(max_length=20)),
                ('other_details', models.TextField(blank=True)),
            ],
        ),
    ]
