# Generated by Django 3.2 on 2022-11-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roomhire', '0007_roomhire_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomhire',
            name='created_on',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
